version: '3.8'
services:

  arkivgpt-processor:
    container_name: arkivgpt-processor
    build:
      context: ./
      dockerfile: ArkivGPT_Processor/Dockerfile
    networks:
      - grpc-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    #ports:
      #- 5001:5001

  arkivgpt-gateway:
    container_name: arkivgpt-gateway
    build:
      context: ./ArkivGPT_Gateway
      dockerfile: Dockerfile
    depends_on:
      - arkivgpt-processor
    networks:
      - grpc-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - GRPC_SERVER_ADDRESS=http://arkivgpt-processor:5001
    #ports:
     # - 5000:8080

  frontend:
    container_name: arkivgpt-frontend
    build:
      context: ./ArkivGPT_Frontend
      dockerfile: Dockerfile
    networks:
      - grpc-network
    depends_on:
      - arkivgpt-processor
      - arkivgpt-gateway
    #ports:
      #- 3000:3000

  nginx:
    image: nginx:latest
    container_name: arkivgpt-nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      #- ./certbot/www:/var/www/certbot/:ro
      #- ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - "80:80"
      #- "443:443"
    networks:
      - grpc-network
    depends_on:
      - frontend

networks:
  grpc-network:
    driver: bridge
