version: '3.8'
services:

  arkivgpt-processor:
    image: localhost:5000/arkivgpt-processor:latest
    build:
      context: ./
      dockerfile: ArkivGPT_Processor/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - GRPC_SERVER_ADDRESS=http://arkivgpt-ocr:5001
    deploy:
      replicas: 1
    volumes:
      - ./Files/:/processor/Files

  arkivgpt-gateway:
    image: localhost:5000/arkivgpt-gateway:latest
    build:
        context: ./ArkivGPT_Gateway
        dockerfile: Dockerfile
    depends_on:
      - arkivgpt-processor
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - GRPC_SERVER_ADDRESS=http://arkivgpt-processor:5001
    volumes:
      - ./Files/:/gateway/Files

  frontend:
    image: localhost:5000/frontend:latest
    build:
      context: ./ArkivGPT_Frontend
      dockerfile: Dockerfile

  arkivgpt-ocr:
   image: localhost:5000/arkivgpt-ocr:latest
   build:
     context: ./ArkivGPT_OCR
     dockerfile: Dockerfile
   depends_on:
     - arkivgpt-processor
   volumes:
     - ./Files/:/ocr/Files


  nginx:
    image: docker.io/nginx:latest
    container_name: arkivgpt-nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      #- ./certbot/www:/var/www/certbot/:ro
      #- ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - "80:80"
      #- "443:443"
    depends_on:
      - frontend 

